manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: RealET
      url-base: https://github.com/RealET
  projects:
    - name: zmk
      remote: RealET
      revision: main
      import: app/west.yml
  self:
    path: config
