manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/RealET
  projects:
    - name: zmk-macros-nice_nano_v2
      remote: RealET
      revision: main
      import: app/west.yml
  self:
    path: config
