file_format: "1"
id: jeff_trinkle_cyboard
name: JCT's Cyboard
type: shield
url: https://www.cyboard.digital
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - jeff_trinkle_cyboard_left
  - jeff_trinkle_cyboard_right
