file_format: "1"
id: hernandez_cyboard
name: Hernandez Cyboard
type: shield
url: https://www.cyboard.digital
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - hernandez_cyboard_left
  - hernandez_cyboard_right
