file_format: "1"
id: peilert_cyboard
name: Peilert Cyboard
type: shield
url: https://www.cyboard.digital
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - peilert_cyboard_left
  - peilert_cyboard_right
